// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddOutlookAccounts(arg1) {
  return window['go']['main']['App']['AddOutlookAccounts'](arg1);
}

export function CancelUpdate() {
  return window['go']['main']['App']['CancelUpdate']();
}

export function CheckLicense() {
  return window['go']['main']['App']['CheckLicense']();
}

export function CheckUpdate() {
  return window['go']['main']['App']['CheckUpdate']();
}

export function ClearOutlookAccounts() {
  return window['go']['main']['App']['ClearOutlookAccounts']();
}

export function ClearRegisteredOutlookAccounts() {
  return window['go']['main']['App']['ClearRegisteredOutlookAccounts']();
}

export function DeleteOutlookAccount(arg1) {
  return window['go']['main']['App']['DeleteOutlookAccount'](arg1);
}

export function DetectProxy(arg1) {
  return window['go']['main']['App']['DetectProxy'](arg1);
}

export function DownloadUpdate() {
  return window['go']['main']['App']['DownloadUpdate']();
}

export function GetCloudMailConfigs() {
  return window['go']['main']['App']['GetCloudMailConfigs']();
}

export function GetDataDir() {
  return window['go']['main']['App']['GetDataDir']();
}

export function GetLicenseInfo() {
  return window['go']['main']['App']['GetLicenseInfo']();
}

export function GetLogs() {
  return window['go']['main']['App']['GetLogs']();
}

export function GetLuckMailConfigs() {
  return window['go']['main']['App']['GetLuckMailConfigs']();
}

export function GetLuckMailDomains(arg1) {
  return window['go']['main']['App']['GetLuckMailDomains'](arg1);
}

export function GetMoeMailConfigs() {
  return window['go']['main']['App']['GetMoeMailConfigs']();
}

export function GetOutlookAccounts() {
  return window['go']['main']['App']['GetOutlookAccounts']();
}

export function GetOverview() {
  return window['go']['main']['App']['GetOverview']();
}

export function GetProxy() {
  return window['go']['main']['App']['GetProxy']();
}

export function GetResultOutputDir() {
  return window['go']['main']['App']['GetResultOutputDir']();
}

export function GetStatus() {
  return window['go']['main']['App']['GetStatus']();
}

export function GetSubscriptionLink(arg1, arg2) {
  return window['go']['main']['App']['GetSubscriptionLink'](arg1, arg2);
}

export function GetSubscriptionPlans(arg1) {
  return window['go']['main']['App']['GetSubscriptionPlans'](arg1);
}

export function GetTaskStatus() {
  return window['go']['main']['App']['GetTaskStatus']();
}

export function GetTempMailLolConfigs() {
  return window['go']['main']['App']['GetTempMailLolConfigs']();
}

export function GetYYDSMailConfigs() {
  return window['go']['main']['App']['GetYYDSMailConfigs']();
}

export function ImportOutlookFile(arg1) {
  return window['go']['main']['App']['ImportOutlookFile'](arg1);
}

export function LoadOutputAccounts() {
  return window['go']['main']['App']['LoadOutputAccounts']();
}

export function LogoutLicense() {
  return window['go']['main']['App']['LogoutLicense']();
}

export function OpenURL(arg1) {
  return window['go']['main']['App']['OpenURL'](arg1);
}

export function ResetDataDir() {
  return window['go']['main']['App']['ResetDataDir']();
}

export function ResetProxy() {
  return window['go']['main']['App']['ResetProxy']();
}

export function ResetResultOutputDir() {
  return window['go']['main']['App']['ResetResultOutputDir']();
}

export function SaveCloudMailConfigs(arg1) {
  return window['go']['main']['App']['SaveCloudMailConfigs'](arg1);
}

export function SaveLuckMailConfigs(arg1) {
  return window['go']['main']['App']['SaveLuckMailConfigs'](arg1);
}

export function SaveMoeMailConfigs(arg1) {
  return window['go']['main']['App']['SaveMoeMailConfigs'](arg1);
}

export function SaveTempMailLolConfigs(arg1) {
  return window['go']['main']['App']['SaveTempMailLolConfigs'](arg1);
}

export function SaveYYDSMailConfigs(arg1) {
  return window['go']['main']['App']['SaveYYDSMailConfigs'](arg1);
}

export function SelectDirectory() {
  return window['go']['main']['App']['SelectDirectory']();
}

export function SelectOutlookFile() {
  return window['go']['main']['App']['SelectOutlookFile']();
}

export function SetDataDir(arg1) {
  return window['go']['main']['App']['SetDataDir'](arg1);
}

export function SetProxy(arg1) {
  return window['go']['main']['App']['SetProxy'](arg1);
}

export function SetResultOutputDir(arg1) {
  return window['go']['main']['App']['SetResultOutputDir'](arg1);
}

export function StartTask(arg1) {
  return window['go']['main']['App']['StartTask'](arg1);
}

export function StopTask() {
  return window['go']['main']['App']['StopTask']();
}

export function TestCloudMailConnection(arg1) {
  return window['go']['main']['App']['TestCloudMailConnection'](arg1);
}

export function TestLuckMailConnection(arg1) {
  return window['go']['main']['App']['TestLuckMailConnection'](arg1);
}

export function TestMoeMailConnection(arg1) {
  return window['go']['main']['App']['TestMoeMailConnection'](arg1);
}

export function TestTempMailLolConnection(arg1) {
  return window['go']['main']['App']['TestTempMailLolConnection'](arg1);
}

export function TestYYDSMailConnection(arg1) {
  return window['go']['main']['App']['TestYYDSMailConnection'](arg1);
}

export function VerifyLicense(arg1) {
  return window['go']['main']['App']['VerifyLicense'](arg1);
}
